# Generated by Django 2.0.7 on 2018-07-18 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('is_draft', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_created', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
