# Generated by Django 2.0.7 on 2018-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180718_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='upload3.jpeg', upload_to=''),
        ),
    ]
