# Generated by Django 2.0.7 on 2018-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='upload3.jpeg', upload_to='publisher_image'),
        ),
    ]
