# Generated by Django 2.0.7 on 2018-07-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180726_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='media/upload3.jpeg', upload_to='publisher_image'),
        ),
    ]
